version: '3'

services:
  dnsmasq:
    build:
      context: "."
      dockerfile: "Dockerfile"
    volumes:
      - $PWD/tftpboot:/srv
    network_mode: "host"
    ports:
      - 67:67
      - 69:69
