version: '3'

services:
  dnsmasq:
    build:
      context: "./dnsmasq"
      dockerfile: "Dockerfile"
    network_mode: "host"
    ports:
      - 67:67
      - 69:69
  nfs:
    build:
      context: "./nfs"
      dockerfile: "Dockerfile"
    ports:
      - 2049:2049
    tty: true
